// <auto-generated />
using System;
using ListaSpesa_BackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListaSpesa_BackEnd.Migrations
{
    [DbContext(typeof(ListaSpesaContext))]
    partial class ListaSpesaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Articolo", b =>
                {
                    b.Property<int>("IdArticolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticolo"));

                    b.Property<bool>("DaComprareSiNo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataScadenzaOfferta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NomeArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeNegozio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrezzoNormale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrezzoOfferta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Priorita")
                        .HasColumnType("int");

                    b.Property<int>("Quantità")
                        .HasColumnType("int");

                    b.Property<string>("UnitaMisura")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArticolo");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("NomeArticolo")
                        .IsUnique();

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("ListaSpesa_BackEnd.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Articolo", b =>
                {
                    b.HasOne("ListaSpesa_BackEnd.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
